# -*- coding: utf-8 -*-
"""demo1_middleware_observability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQsWZpmPrif90AZvv0GYzQqOgBhS2Y8o

# 🔬 Demo 1 — FastAPI Middleware & Observability
> **EY Backend Engineering Bootcamp — Day 9**

**Scenario:** You are an EY backend engineer on a global payments modernisation project. In this demo you will build and test the four middleware pillars — Logging, Metrics, Retry, and Circuit Breaker — that every production FastAPI service must have.

---
### Learning Objectives
- Attach HTTP middleware to a FastAPI app (logging + metrics)
- Use `structlog` for structured JSON logging with correlation IDs
- Expose a `/metrics` endpoint for Prometheus scraping
- Implement exponential-backoff retry with `tenacity`
- Implement a circuit breaker with `pybreaker`

### 🗺️ Road Map
```
Part 1 → Install deps
Part 2 → Logging middleware
Part 3 → Prometheus metrics middleware
Part 4 → Retry with tenacity
Part 5 → Circuit breaker with pybreaker
Part 6 → Run the full app (ngrok tunnel)
Extension Tasks →  Advanced challenges
```

## Part 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install fastapi uvicorn[standard] structlog tenacity pybreaker \
#              prometheus-client prometheus-fastapi-instrumentator \
#              httpx pyngrok nest-asyncio

import nest_asyncio
nest_asyncio.apply()  # Allow asyncio inside Colab's event loop
print('✅ Dependencies installed and asyncio patched')

"""---
## Part 2 — Structured Logging Middleware

Every request must carry a **correlation ID** so you can trace a single payment across 50 microservices.
We attach middleware that:
1. Reads `X-Correlation-Id` from the incoming request (or generates a new UUID)
2. Logs request start / end as structured JSON
3. Passes the correlation ID forward in the response
"""

import structlog, logging, uuid, time
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Configure structlog to output clean JSON
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.PrintLoggerFactory(),
)

log = structlog.get_logger()

app = FastAPI(title='EY Payment API', version='1.0.0')

@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))
    start = time.perf_counter()

    log.info('request.started',
             path=request.url.path,
             method=request.method,
             correlation_id=correlation_id)

    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

    log.info('request.completed',
             path=request.url.path,
             status=response.status_code,
             latency_ms=elapsed_ms,
             correlation_id=correlation_id)

    response.headers['X-Correlation-Id'] = correlation_id
    return response

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    log.info('payment.received', amount=body.get('amount'), currency=body.get('currency', 'GBP'))
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', **body}

print('✅ Logging middleware and routes defined')

"""---
## Part 3 — Prometheus Metrics Middleware

The four golden signals: **Latency, Traffic, Errors, Saturation**. We track all four with Prometheus counters and histograms.
"""

from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from prometheus_fastapi_instrumentator import Instrumentator
from fastapi.responses import Response

# Custom business metric: track payment amounts by currency
PAYMENT_AMOUNT = Histogram(
    'payment_amount_gbp', 'Payment amount in GBP',
    buckets=[10, 50, 100, 500, 1000, 5000, 10000]
)

ERROR_COUNT = Counter(
    'payment_errors_total', 'Total payment processing errors',
    ['error_type']
)

# Auto-instrument all HTTP routes (latency, status codes, method)
Instrumentator().instrument(app).expose(app)

print('✅ Prometheus metrics instrumented')
print('   → /metrics endpoint is now available')
print('   → Tracking: request_count, request_latency, payment_amount')

"""---
## Part 4 — Retry Logic with Tenacity

Payment APIs are flaky under load. We use `tenacity` to retry failed calls with **exponential backoff + jitter** to avoid the thundering herd problem.
"""

import random
import asyncio
from tenacity import (
    retry, stop_after_attempt, wait_exponential,
    retry_if_exception_type, before_sleep_log
)

# Simulate a flaky downstream fraud-check service
call_count = 0

async def flaky_fraud_check(payload: dict) -> dict:
    global call_count
    call_count += 1
    # Fail the first 2 attempts, succeed on 3rd
    if call_count < 3:
        print(f'  ⚠️  Attempt {call_count}: fraud API timeout (simulated)')
        raise ConnectionError(f'Fraud API timeout on attempt {call_count}')
    print(f'  ✅ Attempt {call_count}: fraud check passed')
    return {'fraud_score': 0.02, 'decision': 'approved'}


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=1, min=0.1, max=2),  # seconds (small for demo)
    retry=retry_if_exception_type((ConnectionError, TimeoutError)),
    reraise=True
)
async def call_fraud_api_with_retry(payload: dict) -> dict:
    return await flaky_fraud_check(payload)


# Test it
print('🔄 Testing retry logic...')
result = asyncio.run(
    call_fraud_api_with_retry({'amount': 1500, 'currency': 'GBP'})
)
print(f'\n📦 Final result: {result}')

"""---
## Part 5 — Circuit Breaker with PyBreaker

If a downstream service is consistently failing, retrying indefinitely makes things **worse**. The circuit breaker trips after `N` failures and returns a fast fallback for 30 seconds — preventing cascade failures.
"""

import pybreaker

class LoggingListener(pybreaker.CircuitBreakerListener):
    def state_change(self, cb, old_state, new_state):
        log.warning('circuit_breaker.state_change',
                    breaker=cb.name,
                    old=str(old_state),
                    new=str(new_state))

fraud_breaker = pybreaker.CircuitBreaker(
    fail_max=3,
    reset_timeout=30,
    listeners=[LoggingListener()],
    name='fraud-api'
)

def check_fraud_cb(payload: dict) -> dict:
    """Wrapped by circuit breaker — raises CircuitBreakerError when OPEN."""
    # Simulate always-failing service for demo
    raise ConnectionError('Fraud service down')

def safe_fraud_check(payload: dict) -> dict:
    """Call fraud API with circuit breaker; return fallback if circuit is OPEN."""
    try:
        return fraud_breaker.call(check_fraud_cb, payload)
    except pybreaker.CircuitBreakerError:
        print('🔴 Circuit OPEN — returning safe fallback (manual review)')
        return {'fraud_score': None, 'decision': 'manual_review', 'circuit': 'open'}
    except Exception as e:
        return {'fraud_score': None, 'decision': 'error', 'reason': str(e)}

print('📊 Simulating calls to a failing fraud service...')
for i in range(6):
    result = safe_fraud_check({'amount': 200 * (i + 1)})
    print(f'  Call {i+1}: {result} | Circuit state: {fraud_breaker.current_state}')

"""---
## Part 6 — Run the Full App

We start uvicorn in the background and expose it via a public ngrok tunnel so you can hit it from your browser or Postman.
"""

# ⚠️ You need a free ngrok account. Get your token at https://dashboard.ngrok.com
NGROK_TOKEN = '3Et2LrghqFiCOFPMUlNt7js0hP0_3JuLDFqv3dLENbKDu15zV'  # ← replace this

import threading, uvicorn
from pyngrok import ngrok, conf

conf.get_default().auth_token = NGROK_TOKEN
# TO THIS:
def run_server():
    import asyncio
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    config = uvicorn.Config(app, host='0.0.0.0', port=8000, log_level='warning')
    server = uvicorn.Server(config)
    loop.run_until_complete(server.serve())

thread = threading.Thread(target=run_server, daemon=True)
thread.start()

import time; time.sleep(2)
tunnel = ngrok.connect(8000)
public_url = tunnel.public_url

print(f'🌐 Public URL: {public_url}')
print(f'   Health:   {public_url}/health/ready')
print(f'   Metrics:  {public_url}/metrics')
print(f'   Docs:     {public_url}/docs')

# Quick smoke tests using httpx
import httpx, json

BASE = public_url  # set in the cell above

with httpx.Client() as client:
    # 1 — Health check
    r = client.get(f'{BASE}/health/ready')
    print('Health:', r.json())

    # 2 — POST a payment (watch structured logs above)
    r = client.post(f'{BASE}/payments',
                    json={'amount': 1500, 'currency': 'GBP', 'account': 'ACC-42'},
                    headers={'X-Correlation-Id': 'demo-corr-001'})
    print('Payment:', r.json())
    print('Returned correlation ID:', r.headers.get('X-Correlation-Id'))

    # 3 — Peek at first 500 chars of /metrics
    r = client.get(f'{BASE}/metrics')
    print('\nMetrics (first 500 chars):')
    print(r.text[:500])

"""---
## 🔥 Extension Tasks

### Extension A — Rate-Limiting Middleware *(Medium)*
Add a sliding-window rate limiter (e.g., 100 req/min per client IP) using an in-memory dictionary.
- Return `429 Too Many Requests` with a `Retry-After` header when the limit is exceeded
- Track limit hits as a Prometheus `Counter`

### Extension B — Correlation ID Propagation *(Medium)*
The current middleware assigns a correlation ID but does NOT forward it to outbound `httpx` calls.
- Add a `contextvars.ContextVar` to store the correlation ID per request
- Write a custom `httpx.Auth` or event hook that injects `X-Correlation-Id` into every outbound call
- Verify it appears in mock downstream requests

### Extension C — Prometheus + Grafana Dashboard *(Advanced)*
- Export your running `/metrics` to a free [Grafana Cloud](https://grafana.com/products/cloud/) account using the Prometheus remote-write endpoint
- Build a dashboard with 4 panels: request rate, p99 latency, error rate, circuit breaker trip count

### Extension D — Structured Log Aggregation *(Advanced)*
- Set up a free [Elastic Cloud](https://www.elastic.co/cloud/) cluster or use the Colab local filesystem
- Configure `structlog` to write logs as newline-delimited JSON to a file
- Write a query that finds all requests with `latency_ms > 200` for a specific `correlation_id`
"""
# -*- coding: utf-8 -*-
"""
demo1_extensions.py
EY Backend Engineering Bootcamp — Day 9
All 4 Extension Tasks in one file.

Extension A — Sliding-window rate limiter middleware     (lines ~40)
Extension B — Correlation ID propagation via ContextVar (lines ~90)
Extension C — Prometheus metrics + Grafana config       (lines ~150)
Extension D — Structured NDJSON log aggregation         (lines ~210)
"""

# ── Shared imports ────────────────────────────────────────────────────────────
import uuid, time, json, random, asyncio, collections, logging
import contextvars
from pathlib import Path
from datetime import datetime, timezone

import structlog, httpx, pybreaker
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, Response
from prometheus_client import (
    Counter, Histogram, Gauge,
    generate_latest, CONTENT_TYPE_LATEST,
)

# =============================================================================
# EXTENSION A — Sliding-window Rate Limiter
# =============================================================================
RATE_LIMIT_HITS = Counter(
    "rate_limit_hits_total",
    "Requests rejected by rate limiter",
    ["client_ip"],
)
_windows: dict[str, collections.deque] = {}
LIMIT, WINDOW_S = 100, 60          # 100 req / 60 s per IP

def is_rate_limited(ip: str) -> tuple[bool, int]:
    now = time.monotonic()
    dq  = _windows.setdefault(ip, collections.deque())
    while dq and now - dq[0] > WINDOW_S:
        dq.popleft()
    if len(dq) >= LIMIT:
        return True, int(WINDOW_S - (now - dq[0])) + 1
    dq.append(now)
    return False, 0

# =============================================================================
# EXTENSION B — Correlation ID ContextVar + httpx propagation
# =============================================================================
correlation_id_var: contextvars.ContextVar[str] = contextvars.ContextVar(
    "correlation_id", default=""
)

def inject_correlation_id(req: httpx.Request) -> None:
    corr = correlation_id_var.get("")
    if corr:
        req.headers["X-Correlation-Id"] = corr

def make_http_client() -> httpx.AsyncClient:
    """Every client created here auto-injects the correlation ID."""
    return httpx.AsyncClient(event_hooks={"request": [inject_correlation_id]})

# =============================================================================
# EXTENSION C — Prometheus 4 Golden Signals
# =============================================================================
REQUEST_COUNT = Counter(
    "http_requests_total", "Total HTTP requests",
    ["method", "path", "status"],
)
REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds", "Request latency",
    ["method", "path"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5],
)
ACTIVE_REQUESTS = Gauge("http_active_requests", "In-flight requests")
CB_STATE        = Gauge(
    "circuit_breaker_state",
    "CB state (0=closed 1=open 2=half-open)",
    ["name"],
)
PAYMENT_AMOUNT  = Histogram(
    "payment_amount_gbp", "Payment amount GBP",
    buckets=[10, 50, 100, 500, 1000, 5000, 10000],
)

CB_STATE_MAP = {"closed": 0, "open": 1, "half-open": 2}

class CBMetricListener(pybreaker.CircuitBreakerListener):
    def state_change(self, cb, old, new):
        CB_STATE.labels(name=cb.name).set(CB_STATE_MAP.get(str(new), 0))

fraud_cb = pybreaker.CircuitBreaker(
    fail_max=3, reset_timeout=30,
    listeners=[CBMetricListener()], name="fraud-api",
)

GRAFANA_DASHBOARD = {
    "title": "EY Payment API — 4 Golden Signals",
    "panels": [
        {"title": "Request Rate (req/s)",   "targets": [{"expr": "rate(http_requests_total[1m])"}]},
        {"title": "p99 Latency (ms)",        "targets": [{"expr": "histogram_quantile(0.99,rate(http_request_duration_seconds_bucket[5m]))*1000"}]},
        {"title": "Error Rate (%)",          "targets": [{"expr": "sum(rate(http_requests_total{status=~'5..'}[5m]))/sum(rate(http_requests_total[5m]))*100"}]},
        {"title": "Circuit Breaker State",   "targets": [{"expr": "circuit_breaker_state"}]},
    ],
}

PROMETHEUS_YML = """
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'payment-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
"""

# =============================================================================
# EXTENSION D — NDJSON Structured Log Aggregation
# =============================================================================
LOG_DIR  = Path("logs")
LOG_FILE = LOG_DIR / "app.log"
LOG_DIR.mkdir(exist_ok=True)

_file_handler = logging.FileHandler(LOG_FILE, encoding="utf-8")
_file_handler.setFormatter(logging.Formatter("%(message)s"))
logging.getLogger().addHandler(_file_handler)
logging.getLogger().setLevel(logging.DEBUG)

# TO THIS:
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.PrintLoggerFactory(),
)
log = structlog.get_logger()

class LogQuery:
    def __init__(self, path: Path = LOG_FILE):
        self.lines = self._load(path)

    def _load(self, path: Path) -> list[dict]:
        if not path.exists():
            return []
        records = []
        for raw in path.read_text(encoding="utf-8").splitlines():
            raw = raw.strip()
            try:
                idx = raw.index("{")
                records.append(json.loads(raw[idx:]))
            except (ValueError, json.JSONDecodeError):
                pass
        return records

    def where(self, **kw) -> "LogQuery":
        return self._clone([r for r in self.lines if all(r.get(k)==v for k,v in kw.items())])

    def where_gt(self, field: str, value: float) -> "LogQuery":
        return self._clone([r for r in self.lines if r.get(field, 0) > value])

    def select(self, *fields) -> list[dict]:
        return [{f: r.get(f) for f in fields} for r in self.lines]

    def count(self) -> int:
        return len(self.lines)

    def _clone(self, lines) -> "LogQuery":
        q = LogQuery.__new__(LogQuery)
        q.lines = lines
        return q

# =============================================================================
# FASTAPI APP — all middleware + routes wired together
# =============================================================================
app = FastAPI(title="EY Payment API — Extensions A–D", version="2.0.0")

# ── Middleware A: Rate limiter ─────────────────────────────────────────────
@app.middleware("http")
async def rate_limit_middleware(request: Request, call_next):
    ip = request.client.host or "unknown"
    limited, retry_after = is_rate_limited(ip)
    if limited:
        RATE_LIMIT_HITS.labels(client_ip=ip).inc()
        return JSONResponse(
            status_code=429,
            content={"error": "Too Many Requests",
                     "retry_after_seconds": retry_after},
            headers={"Retry-After": str(retry_after)},
        )
    return await call_next(request)

# ── Middleware B: Correlation ID ContextVar ────────────────────────────────
@app.middleware("http")
async def correlation_middleware(request: Request, call_next):
    corr_id = request.headers.get("X-Correlation-Id", str(uuid.uuid4()))
    token   = correlation_id_var.set(corr_id)
    try:
        response = await call_next(request)
        response.headers["X-Correlation-Id"] = corr_id
        return response
    finally:
        correlation_id_var.reset(token)

# ── Middleware C: Prometheus metrics ───────────────────────────────────────
@app.middleware("http")
async def metrics_middleware(request: Request, call_next):
    ACTIVE_REQUESTS.inc()
    start    = time.perf_counter()
    response = await call_next(request)
    duration = time.perf_counter() - start
    REQUEST_COUNT.labels(method=request.method,
                         path=request.url.path,
                         status=response.status_code).inc()
    REQUEST_LATENCY.labels(method=request.method,
                           path=request.url.path).observe(duration)
    ACTIVE_REQUESTS.dec()
    return response

# ── Middleware D: Structured logging ──────────────────────────────────────
@app.middleware("http")
async def logging_middleware(request: Request, call_next):
    start   = time.perf_counter()
    corr_id = correlation_id_var.get(str(uuid.uuid4()))
    log.info("request.started", path=request.url.path,
             method=request.method, correlation_id=corr_id)
    response    = await call_next(request)
    latency_ms  = round((time.perf_counter() - start) * 1000, 2)
    log.info("request.completed", path=request.url.path,
             status=response.status_code, latency_ms=latency_ms,
             correlation_id=corr_id)
    return response

# ── Routes ────────────────────────────────────────────────────────────────
@app.get("/health")
async def health():
    return {"status": "ok", "extensions": ["A-rate-limit","B-corr-id","C-prometheus","D-logging"]}

@app.post("/payments")
async def create_payment(request: Request):
    body   = await request.json()
    amount = float(body.get("amount", 0))
    PAYMENT_AMOUNT.observe(amount)
    async with make_http_client() as client:
        fraud = await client.get("http://localhost:8000/downstream/fraud-check")
    return {"payment_id": str(uuid.uuid4()), "status": "accepted",
            "fraud": fraud.json(), **body}

@app.get("/downstream/fraud-check")
async def mock_fraud_check(request: Request):
    received_corr = request.headers.get("X-Correlation-Id", "MISSING")
    return {"fraud_score": 0.02, "decision": "approved",
            "received_correlation_id": received_corr}

@app.get("/metrics")
async def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)

@app.get("/logs/query")
async def query_logs(latency_gt: float = 0.0, status: int = None):
    q = LogQuery()
    if latency_gt:
        q = q.where_gt("latency_ms", latency_gt)
    if status:
        q = q.where(status=status)
    return {"count": q.count(), "results": q.select("path","latency_ms","status","correlation_id")}

# =============================================================================
# STANDALONE DEMOS (python demo1_extensions.py)
# =============================================================================
if __name__ == "__main__":
    print("=" * 60)
    print("EXTENSION A — Rate Limiter (limit=10 for demo)")
    print("=" * 60)
    LIMIT = 10
    for i in range(13):
        limited, retry = is_rate_limited("10.0.0.1")
        status = f"🔴 429  Retry-After:{retry}s" if limited else "✅ 200  OK"
        print(f"  Request {i+1:>2}: {status}")

    print("\n" + "=" * 60)
    print("EXTENSION B — ContextVar isolation (5 concurrent requests)")
    print("=" * 60)
    async def sim_request(n):
        corr  = f"corr-{n}-{uuid.uuid4().hex[:6]}"
        token = correlation_id_var.set(corr)
        try:
            await asyncio.sleep(0.01)
            got   = correlation_id_var.get()
            match = "✅" if got == corr else "❌"
            print(f"  Request {n}: set={corr} got={got} {match}")
        finally:
            correlation_id_var.reset(token)

    async def run_all(): await asyncio.gather(*[sim_request(i) for i in range(1, 6)])
    asyncio.run(run_all())

    print("\n" + "=" * 60)
    print("EXTENSION C — Prometheus metrics simulation")
    print("=" * 60)
    for i in range(5):
        REQUEST_COUNT.labels(method="POST", path="/payments", status=201).inc()
        REQUEST_LATENCY.labels(method="POST", path="/payments").observe(random.uniform(0.01, 0.3))
        PAYMENT_AMOUNT.observe(random.uniform(10, 5000))
        print(f"  Tick {i+1}: request+payment metric recorded")
    print(f"  Grafana dashboard panels: {[p['title'] for p in GRAFANA_DASHBOARD['panels']]}")
    print(f"  prometheus.yml ready for docker-compose scraping")

    print("\n" + "=" * 60)
    print("EXTENSION D — NDJSON log queries")
    print("=" * 60)
    corr_ids = [str(uuid.uuid4()) for _ in range(4)]
    for i in range(20):
        log.info("request.completed",
                 path=["/payments","/health","/metrics","/payments"][i%4],
                 status=200 if i%7!=0 else 500,
                 latency_ms=round(50+(i*37%500), 2),
                 correlation_id=corr_ids[i%4])
    q = LogQuery()
    print(f"  Total lines: {q.count()}")
    slow = q.where_gt("latency_ms", 200)
    print(f"  latency_ms > 200ms : {slow.count()} hits")
    errs = q.where(status=500)
    print(f"  status=500         : {errs.count()} hits")
    for r in errs.select("path","latency_ms","correlation_id"):
        print(f"    {r}")
    print(f"  NDJSON log → {LOG_FILE.resolve()}")
    print("\n✅ All extensions A–D complete")