_wandb:
    value:
        cli_version: 0.27.2
        e:
            tg489twa5og7j9ty19simo7bbrulm3o1:
                codePath: c:\Users\Administrator\EY-Training-Repo\eytraining\Day-13\colab2_feedback_loop (1).ipynb
                codePathLocal: colab2_feedback_loop (1).ipynb
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "136779730944"
                        used: "78504525824"
                email: qunnaharsabi@gmail.com
                executable: c:\Users\Administrator\AppData\Local\Programs\Python\Python314\python.exe
                git:
                    commit: 92a63a21b71ecc7c924328c984ca15a9606e1cff
                    remote: https://github.com/qunnaharsabi-ux/Webapp.git
                host: 4b13af1fe8c554c
                memory:
                    total: "8588832768"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Administrator\EY-Training-Repo\eytraining\Day-13\colab2_feedback_loop (1).ipynb
                python: CPython 3.14.5
                root: c:\Users\Administrator\EY-Training-Repo\eytraining\Day-13
                startedAt: "2026-06-15T10:00:29.889906Z"
                writerId: tg489twa5og7j9ty19simo7bbrulm3o1
        m: []
        python_version: 3.14.5
        t:
            "1":
                - 11
                - 49
                - 95
                - 97
                - 105
            "2":
                - 11
                - 49
                - 95
                - 97
                - 105
            "3":
                - 2
                - 16
            "4": 3.14.5
            "5": 0.27.2
            "6": 5.9.0
            "8":
                - 1
                - 3
            "12": 0.27.2
            "13": windows-amd64
model:
    value: claude-3-5-sonnet
version:
    value: "2.0"
