# # -*- coding: utf-8 -*-
# """GAN_image_generation_MNIST.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/16OWesReBHqCHK8e1YxTQPnU-ync9AoAX
# """

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# Generator Block
class Generator(nn.Module):
  def __init__(self, z_dim):
    super().__init__()
    self.model = nn.Sequential(
        nn.ConvTranspose2d(z_dim, 256, 7, 1, 0), # Input 1x1, Output 7x7
        nn.BatchNorm2d(256),
        nn.ReLU(),
        nn.ConvTranspose2d(256, 128, 4, 2, 1), # Input 7x7, Output 14x14
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.ConvTranspose2d(128, 1, 4, 2, 1), # Input 14x14, Output 28x28
        nn.Tanh(),
    )
  def forward(self, x):
      return self.model(x)

# Discriminator Block
class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Conv2d(1, 64, 4, 2, 1),
        nn.LeakyReLU(0.2),
        nn.Conv2d(64, 128, 4, 2, 1),
        nn.BatchNorm2d(128),
        nn.LeakyReLU(0.2),
        nn.Flatten(),
        nn.Linear(128*7*7, 1),
        nn.Sigmoid(),
    )

  def forward(self, x):
      return self.model(x)

device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
batch_size = 128
lr = 0.002
z_dim = 100
epochs = 10



# Dataset loading
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Initializing loss function, generator, discriminator and optimizers
criterion = nn.BCELoss()
generator = Generator(z_dim).to(device)
discriminator = Discriminator().to(device)
optimizer_g = optim.Adam(generator.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_d = optim.Adam(discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

def show_images(fake):
  img = fake.detach().cpu()[:16]
  grid = img.view(16, 28, 28)

  fig, axes = plt.subplots(4, 4, figsize=(5, 5))
  for i, ax in enumerate(axes.flatten()):
    ax.imshow(grid[i], cmap='gray')
    ax.axis('off')
  plt.show()

# Training Step
for epoch in range(epochs):
  for real, _ in dataloader:
    real = real.to(device)
    batch_size = real.size(0)

    # Training discriminator
    noise = torch.randn(batch_size, z_dim, 1, 1).to(device)
    fake = generator(noise)

    real_labels = torch.ones(batch_size, 1).to(device)
    # Label Smoothing
    real_labels = torch.ones(batch_size, 1).to(device) * 0.9

    fake_labels = torch.zeros(batch_size, 1).to(device)

    # Real Loss
    D_real = discriminator(real)
    loss_real = criterion(D_real, real_labels)

    # Fake Loss
    D_fake = discriminator(fake.detach())
    loss_fake = criterion(D_fake, fake_labels)

    # Total Loss
    loss_D = loss_real + loss_fake

    optimizer_d.zero_grad()
    loss_D.backward()
    optimizer_d.step()

    # Train Discriminator
    output = discriminator(fake)
    g_loss = criterion(output, real_labels) # wants Discriminator to think fake is real

    optimizer_g.zero_grad()
    g_loss.backward()
    optimizer_g.step()
  show_images(real)
  show_images(fake)
  print(f"Epoch [{epoch}/{epochs}], Loss D: {loss_D.item()}, Loss G: {g_loss.item()}")


# =============================================================================
# EXTENSION TASK: Higher Resolution Image Generation (64x64)
# Original code above is untouched. This section defines separate classes,
# dataset, and training loop for 64x64 generation.
# =============================================================================

# ── High-Res Generator: 1x1 → 4x4 → 8x8 → 16x16 → 32x32 → 64x64 ──────────
class Generator64(nn.Module):
    def __init__(self, z_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.ConvTranspose2d(z_dim, 512, 4, 1, 0),   # 1x1  → 4x4
            nn.BatchNorm2d(512),
            nn.ReLU(True),
            nn.ConvTranspose2d(512, 256, 4, 2, 1),     # 4x4  → 8x8
            nn.BatchNorm2d(256),
            nn.ReLU(True),
            nn.ConvTranspose2d(256, 128, 4, 2, 1),     # 8x8  → 16x16
            nn.BatchNorm2d(128),
            nn.ReLU(True),
            nn.ConvTranspose2d(128, 64, 4, 2, 1),      # 16x16 → 32x32
            nn.BatchNorm2d(64),
            nn.ReLU(True),
            nn.ConvTranspose2d(64, 1, 4, 2, 1),        # 32x32 → 64x64
            nn.Tanh(),
        )

    def forward(self, x):
        return self.model(x)


# ── High-Res Discriminator: 64x64 → 32x32 → 16x16 → 8x8 → 4x4 → 1x1 ──────
# Uses a final Conv2d instead of Flatten+Linear so it isn't tied to image size
class Discriminator64(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Conv2d(1, 64, 4, 2, 1),                 # 64x64 → 32x32
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(64, 128, 4, 2, 1),               # 32x32 → 16x16
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(128, 256, 4, 2, 1),              # 16x16 → 8x8
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(256, 512, 4, 2, 1),              # 8x8   → 4x4
            nn.BatchNorm2d(512),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(512, 1, 4, 1, 0),                # 4x4   → 1x1
            nn.Sigmoid(),
        )

    def forward(self, x):
        return self.model(x).view(-1, 1)               # flatten to (batch, 1)


# ── DCGAN weight initialisation for stable training ─────────────────────────
def weights_init(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find('BatchNorm') != -1:
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0)


# ── show_images for 64x64 output ────────────────────────────────────────────
def show_images_64(fake, title="Generated 64x64 Images"):
    img = fake.detach().cpu()[:16]
    img = (img * 0.5 + 0.5).clamp(0, 1)    # denormalise [-1,1] → [0,1]
    grid = img.view(16, 64, 64)

    fig, axes = plt.subplots(4, 4, figsize=(6, 6))
    fig.suptitle(title, fontsize=12)
    for i, ax in enumerate(axes.flatten()):
        ax.imshow(grid[i], cmap='gray')
        ax.axis('off')
    plt.tight_layout()
    plt.show()


# ── Hyperparameters for 64x64 training ──────────────────────────────────────
batch_size_64 = 64      # smaller batch — 64x64 images use 4x more GPU memory
lr_64         = 0.0002  # lower LR for stable high-res training
epochs_64     = 30      # more epochs needed for higher resolution convergence
z_dim_64      = 100     # same latent dimension as original

# ── Dataset: MNIST upsampled to 64x64 ───────────────────────────────────────
transform_64 = transforms.Compose([
    transforms.Resize(64),                  # upsample 28x28 → 64x64
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset_64    = datasets.MNIST(root='./data', train=True, download=True, transform=transform_64)
dataloader_64 = DataLoader(dataset_64, batch_size=batch_size_64, shuffle=True)

# ── Models, weight init, loss, optimisers ───────────────────────────────────
criterion_64    = nn.BCELoss()
generator_64    = Generator64(z_dim_64).to(device)
discriminator_64 = Discriminator64().to(device)

generator_64.apply(weights_init)
discriminator_64.apply(weights_init)

optimizer_g64 = optim.Adam(generator_64.parameters(),     lr=lr_64, betas=(0.5, 0.999))
optimizer_d64 = optim.Adam(discriminator_64.parameters(), lr=lr_64, betas=(0.5, 0.999))

# Fixed noise to track visual progress consistently across epochs
fixed_noise_64 = torch.randn(16, z_dim_64, 1, 1).to(device)

# ── Training loop for 64x64 ─────────────────────────────────────────────────
for epoch in range(epochs_64):
    for real_64, _ in dataloader_64:
        real_64    = real_64.to(device)
        curr_batch = real_64.size(0)

        # Train Discriminator
        noise_64   = torch.randn(curr_batch, z_dim_64, 1, 1).to(device)
        fake_64    = generator_64(noise_64)

        real_labels_64 = torch.ones(curr_batch, 1).to(device) * 0.9  # label smoothing
        fake_labels_64 = torch.zeros(curr_batch, 1).to(device)

        D_real_64    = discriminator_64(real_64)
        loss_real_64 = criterion_64(D_real_64, real_labels_64)

        D_fake_64    = discriminator_64(fake_64.detach())
        loss_fake_64 = criterion_64(D_fake_64, fake_labels_64)

        loss_D_64 = loss_real_64 + loss_fake_64
        optimizer_d64.zero_grad()
        loss_D_64.backward()
        optimizer_d64.step()

        # Train Generator
        output_64 = discriminator_64(fake_64)
        loss_G_64 = criterion_64(output_64, torch.ones(curr_batch, 1).to(device))

        optimizer_g64.zero_grad()
        loss_G_64.backward()
        optimizer_g64.step()

    # Show progress every 5 epochs using fixed noise
    if (epoch + 1) % 5 == 0 or epoch == 0:
        with torch.no_grad():
            sample_64 = generator_64(fixed_noise_64)
        show_images_64(sample_64, title=f"Epoch {epoch+1} — 64x64 Generated Digits")

    print(f"Epoch [{epoch+1}/{epochs_64}], Loss D: {loss_D_64.item():.4f}, Loss G: {loss_G_64.item():.4f}")
