# -*- coding: utf-8 -*-
"""Semantic search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufNq5rxqT28fvLoi5-tYp8EPQD_7zYE6
"""

# Install sentence-transformers for semantic search and rank-bm25 for keyword search
# !pip install -q sentence-transformers rank-bm25

import numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, util

# Sample corporate/tech dataset
corpus = [
    "How to hard-reset your iPhone 13 if the touch screen is completely frozen or unresponsive.", # Doc 0
    "Troubleshooting guide for iOS updates failing on newer Apple mobile devices.",              # Doc 1
    "The new Samsung Galaxy S26 Ultra features an advanced generative AI camera system.",         # Doc 2
    "Steps to recover a lost Google Pixel account recovery phrase or authentication token.",    # Doc 3
    "Fixing Wi-Fi connectivity drops and network configuration errors on Apple Macbook laptops.", # Doc 4
    "Why is my smartphone battery draining so quickly? Top power optimization tips.",            # Doc 5
]

print(f"Loaded database with {len(corpus)} technical documents.")

# Tokenize corpus for BM25 processing
tokenized_corpus = [doc.lower().split(" ") for doc in corpus]
bm25 = BM25Okapi(tokenized_corpus)

def sparse_search(query, top_n=5):
    """Executes keyword lookup and returns sorted document indices and raw scores."""
    tokenized_query = query.lower().split(" ")
    scores = bm25.get_scores(tokenized_query)
    # Sort indices by score descending
    top_indices = np.argsort(scores)[::-1][:top_n]

    # Return list of tuples: (doc_id, score)
    return [(idx, scores[idx]) for idx in top_indices if scores[idx] > 0]

# Quick verification test
print("Sparse test search for 'iPhone 13':", sparse_search("iPhone 13"))

# Initialize a lightweight, high-performance bi-encoder model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Generate dense vector embeddings for the entire corpus
corpus_embeddings = embedding_model.encode(corpus, convert_to_tensor=True)

def dense_search(query, top_n=5):
    """Executes semantic search via cosine similarity and returns sorted indices and scores."""
    query_embedding = embedding_model.encode(query, convert_to_tensor=True)

    # Calculate cosine similarity matrix against all corpus documents
    cos_scores = util.cos_sim(query_embedding, corpus_embeddings)[0]

    # Sort top elements
    top_results = np.argsort(cos_scores.cpu().numpy())[::-1][:top_n]

    return [(int(idx), float(cos_scores[idx])) for idx in top_results]

# Quick verification test
print("Dense test search for 'pixels in camera':", dense_search("pixels in camera"))

def reciprocal_rank_fusion(sparse_results, dense_results, k=60, top_n=3):
    """
    Fuses rankings from separate systems using the Reciprocal Rank Fusion formula.
    Inputs are expected to be lists of tuples: (doc_id, score) sorted by relevance.
    """
    rrf_scores = {}

    # Process sparse rankings
    for rank, (doc_id, _) in enumerate(sparse_results):
        # rank starts at 0, so rank position is rank + 1
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + (rank + 1))

    # Process dense rankings
    for rank, (doc_id, _) in enumerate(dense_results):
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + (rank + 1))

    # Sort documents based on their combined RRF metrics
    fused_rankings = sorted(rrf_scores.items(), key=lambda item: item[1], reverse=True)

    return fused_rankings[:top_n]

def hybrid_search_engine(query, top_n=3):
    """Orchestrates both systems and fuses the output."""
    # 1. Gather deep recall arrays from both engines
    sparse_res = sparse_search(query, top_n=10)
    dense_res = dense_search(query, top_n=10)

    # 2. Fuse the rankings using RRF
    hybrid_res = reciprocal_rank_fusion(sparse_res, dense_res, k=60, top_n=top_n)

    # 3. Print pretty outputs for comparison
    print(f"\n==== TARGET QUERY: '{query}' ====")
    for rank, (doc_id, rrf_score) in enumerate(hybrid_res):
        print(f"\n[Rank {rank + 1}] (RRF Score: {rrf_score:.4f})")
        print(f"Document #{doc_id}: {corpus[doc_id]}")

# -----------------------------------------------------------------
# Execution Test 1: The Keyword Trap
# Query uses exact keyword terms from Doc 0, but conceptual theme of Doc 1
hybrid_search_engine("Apple mobile device issues")

# Execution Test 2: Multi-Concept Search
# Query matches semantic context of Doc 5 but specific tech hardware in Doc 4
hybrid_search_engine("Macbook laptop battery optimization")

# =============================================================================
# EXTENSION C: Search Evaluation Metrics — MRR & NDCG
# =============================================================================
# Introduces a ground-truth test set and formally evaluates all three search
# engines (sparse, dense, hybrid) using standard IR metrics:
#
#   MRR  (Mean Reciprocal Rank)
#        Measures how highly the FIRST relevant document is ranked.
#        MRR = mean( 1 / rank_of_first_relevant_doc ) across all queries.
#        Score of 1.0 → every query's top result is relevant.
#        Score of 0.5 → first relevant doc is on average at rank 2.
#
#   NDCG (Normalized Discounted Cumulative Gain) @k
#        Measures the quality of the ENTIRE top-k ranking, rewarding systems
#        that put highly-relevant docs near the top.
#        Uses a log2 discount: documents ranked lower contribute less.
#        Score of 1.0 → perfect ranking; 0.0 → no relevant docs in top-k.
#
# Ground-truth format:
#   Each entry is a dict with:
#     "query"        – the natural-language query string
#     "relevant_ids" – list of doc IDs considered relevant (binary, grade=1)
#     "graded_ids"   – dict {doc_id: grade} for NDCG (grade 2=highly relevant,
#                      1=relevant, 0=not relevant)
# =============================================================================

import math

# ---------------------------------------------------------------------------
# Ground-Truth Test Set
# ---------------------------------------------------------------------------
# 8 queries covering keyword-heavy, semantic, and multi-concept cases so the
# evaluation exercises both the sparse and dense legs of the hybrid engine.

ground_truth = [
    {
        "query": "iPhone reset frozen screen",
        "relevant_ids": [0],
        "graded_ids": {0: 2, 1: 1},  # Doc 0 highly relevant, Doc 1 partly
    },
    {
        "query": "iOS update problems Apple devices",
        "relevant_ids": [1, 0],
        "graded_ids": {1: 2, 0: 1},
    },
    {
        "query": "Samsung AI camera features",
        "relevant_ids": [2],
        "graded_ids": {2: 2},
    },
    {
        "query": "Google Pixel account recovery",
        "relevant_ids": [3],
        "graded_ids": {3: 2},
    },
    {
        "query": "MacBook Wi-Fi network issues",
        "relevant_ids": [4],
        "graded_ids": {4: 2, 5: 0},
    },
    {
        "query": "smartphone battery draining fast",
        "relevant_ids": [5],
        "graded_ids": {5: 2, 4: 1},  # Doc 4 mentions laptops — partially relevant
    },
    {
        "query": "Apple mobile device issues",  # keyword trap — matches Doc 0 & 1
        "relevant_ids": [0, 1, 4],
        "graded_ids": {0: 2, 1: 2, 4: 1},
    },
    {
        "query": "Macbook laptop battery optimization",  # multi-concept
        "relevant_ids": [4, 5],
        "graded_ids": {4: 2, 5: 2},
    },
]


# ---------------------------------------------------------------------------
# Retrieval wrappers that return ranked doc-ID lists only
# ---------------------------------------------------------------------------

def retrieve_sparse(query, top_n=6):
    """Returns list of doc_ids ranked by BM25 score (descending)."""
    results = sparse_search(query, top_n=top_n)
    return [doc_id for doc_id, _ in results]


def retrieve_dense(query, top_n=6):
    """Returns list of doc_ids ranked by cosine similarity (descending)."""
    results = dense_search(query, top_n=top_n)
    return [doc_id for doc_id, _ in results]


def retrieve_hybrid(query, top_n=6):
    """Returns list of doc_ids ranked by RRF score (descending)."""
    sparse_res = sparse_search(query, top_n=10)
    dense_res = dense_search(query, top_n=10)
    fused = reciprocal_rank_fusion(sparse_res, dense_res, k=60, top_n=top_n)
    return [doc_id for doc_id, _ in fused]


# ---------------------------------------------------------------------------
# Metric implementations
# ---------------------------------------------------------------------------

def reciprocal_rank(ranked_ids, relevant_ids):
    """
    Computes the reciprocal rank for a single query.
    Returns 1/rank of the first relevant document, or 0 if none found.
    """
    for rank, doc_id in enumerate(ranked_ids, start=1):
        if doc_id in relevant_ids:
            return 1.0 / rank
    return 0.0


def dcg_at_k(ranked_ids, graded_ids, k):
    """
    Computes Discounted Cumulative Gain at cutoff k.
    DCG@k = sum( grade_i / log2(rank_i + 1) ) for i in 1..k
    """
    dcg = 0.0
    for rank, doc_id in enumerate(ranked_ids[:k], start=1):
        grade = graded_ids.get(doc_id, 0)
        dcg += grade / math.log2(rank + 1)
    return dcg


def ndcg_at_k(ranked_ids, graded_ids, k):
    """
    Computes Normalized DCG at cutoff k.
    Divides actual DCG by the ideal DCG (best possible ranking of the grades).
    Returns 0.0 if the ideal DCG is zero (no relevant docs exist).
    """
    # Ideal ranking: sort available grades descending
    ideal_grades = sorted(graded_ids.values(), reverse=True)
    ideal_ranking = list(graded_ids.keys())  # placeholder ids — only grades matter
    ideal_dcg = sum(
        grade / math.log2(rank + 2)  # rank+2 because enumerate starts at 0
        for rank, grade in enumerate(ideal_grades[:k])
    )
    if ideal_dcg == 0.0:
        return 0.0
    actual_dcg = dcg_at_k(ranked_ids, graded_ids, k)
    return actual_dcg / ideal_dcg


# ---------------------------------------------------------------------------
# Evaluation runner
# ---------------------------------------------------------------------------

def evaluate_engine(retrieve_fn, ground_truth, k=3, engine_name="Engine"):
    """
    Runs retrieve_fn over every test query, computes per-query MRR and NDCG@k,
    then prints a detailed breakdown table and macro-averaged summary.

    Args:
        retrieve_fn   : callable(query, top_n) → list[doc_id]
        ground_truth  : list of dicts with keys query/relevant_ids/graded_ids
        k             : cutoff for NDCG (default 3)
        engine_name   : label used in the printed header
    """
    rr_scores = []
    ndcg_scores = []

    header = f"\n{'=' * 65}\n  {engine_name.upper()} — Evaluation @ k={k}\n{'=' * 65}"
    print(header)
    print(f"{'Query':<42} {'RR':>6}  {'NDCG@k':>7}")
    print("-" * 58)

    for item in ground_truth:
        query = item["query"]
        relevant_ids = set(item["relevant_ids"])
        graded_ids = item["graded_ids"]

        ranked = retrieve_fn(query, top_n=max(k, 10))

        rr = reciprocal_rank(ranked, relevant_ids)
        ndcg = ndcg_at_k(ranked, graded_ids, k)

        rr_scores.append(rr)
        ndcg_scores.append(ndcg)

        # Truncate long queries for display
        short_q = (query[:39] + "…") if len(query) > 40 else query
        print(f"  {short_q:<40} {rr:>6.4f}  {ndcg:>7.4f}")

    mrr = np.mean(rr_scores)
    mean_ndcg = np.mean(ndcg_scores)

    print("-" * 58)
    print(f"  {'MACRO AVERAGE':<40} {mrr:>6.4f}  {mean_ndcg:>7.4f}")
    print(f"\n  MRR         = {mrr:.4f}  (higher → first relevant result is ranked earlier)")
    print(f"  Mean NDCG@{k} = {mean_ndcg:.4f}  (higher → better overall top-{k} ranking quality)")
    print("=" * 65)

    return {"MRR": mrr, f"NDCG@{k}": mean_ndcg}


# ---------------------------------------------------------------------------
# Compare all three engines side-by-side
# ---------------------------------------------------------------------------

K = 3  # evaluation cutoff — change to 5 for a broader view

results_sparse = evaluate_engine(retrieve_sparse, ground_truth, k=K, engine_name="Sparse  (BM25)")
results_dense = evaluate_engine(retrieve_dense, ground_truth, k=K, engine_name="Dense   (MiniLM cosine)")
results_hybrid = evaluate_engine(retrieve_hybrid, ground_truth, k=K, engine_name="Hybrid  (BM25 + Dense, RRF)")

# ---------------------------------------------------------------------------
# Summary comparison table
# ---------------------------------------------------------------------------

print(f"\n{'=' * 65}")
print("  FINAL COMPARISON SUMMARY")
print(f"{'=' * 65}")
print(f"  {'Engine':<30} {'MRR':>8}  {'NDCG@' + str(K):>8}")
print("-" * 52)
for name, res in [
    ("Sparse  (BM25)", results_sparse),
    ("Dense   (MiniLM cosine)", results_dense),
    ("Hybrid  (BM25 + Dense, RRF)", results_hybrid),
]:
    print(f"  {name:<30} {res['MRR']:>8.4f}  {res[f'NDCG@{K}']:>8.4f}")
print("=" * 65)
print("\nInterpretation guide:")
print("  MRR  → how quickly each engine surfaces its FIRST relevant result.")
print(f"  NDCG@{K} → quality of the entire top-{K} ranking (penalises wrong order).")
print("  Hybrid should match or beat both individual engines on most queries.")
